### ISSUE TITLE
Unable to generate package name correctly

### ISSUE THREAD

**Issue by WJY-norainu** [jauhararifin/gomocker#1]
Hi @jauhararifin 
It seems `gomocker` may not generate the correct package name if the package path contains special characters like underscore `_`. An example is to run `gomocker --package abc/my_package MyInterfaceToMock`. In this case, the generated file will have `package mypackage`. If the source package is actually `package my_package`, the generated file will cause build errors due to different package names used within the same directory.

I think this comes from the fact that `gomocker` uses `jen.NewFilePath` to create the generated file:
```
// NewFilePath creates a new file while specifying the package path - the
// package name is inferred from the path.
func NewFilePath(packagePath string) *File {
	return &File{
		Group: &Group{
			multi: true,
		},
		name:    guessAlias(packagePath),
		path:    packagePath,
		imports: map[string]importdef{},
		hints:   map[string]importdef{},
	}
}

...

func guessAlias(path string) string {
	alias := path

	if strings.HasSuffix(alias, "/") {
		// training slashes are usually tolerated, so we can get rid of one if
		// it exists
		alias = alias[:len(alias)-1]
	}

	if strings.Contains(alias, "/") {
		// if the path contains a "/", use the last part
		alias = alias[strings.LastIndex(alias, "/")+1:]
	}

	// alias should be lower case
	alias = strings.ToLower(alias)

	// alias should now only contain alphanumerics
	importsRegex := regexp.MustCompile(`[^a-z0-9]`)
	alias = importsRegex.ReplaceAllString(alias, "")

	return alias
}
```

I think this makes sense for `jen` lib. But maybe for `gomocker`, the better way is to use `jen.NewFilePathName` to create the new file if the package is already provided by the user?

**Comment by jauhararifin** [comment]
Thank you @WJY-norainu 
This is actually an issue that I've been meaning to fix from long time ago, but don't have time lol.

I created [This PR](https://github.com/jauhararifin/gomocker/pull/2) to fix this as you suggested, can check if this works for you?

**Comment by WJY-norainu** [comment]
@jauhararifin Thanks for the super prompt reply 😆 
Yup - the PR LGTM.

**Comment by jauhararifin** [comment]
Thank you. You can use this tag: [v1.0.5](https://github.com/jauhararifin/gomocker/releases/tag/v1.0.5).
