### ISSUE TITLE
Feature request: allow mocks to be created in a different package/directory from source files

### ISSUE THREAD

**Issue by WJY-norainu** [jauhararifin/gomocker#3]
Hi @jauhararifin 

I have created this issue as a feature request because I'm not sure if generation of mocks in a different package/directory is supposed to be supported in the first place by `gomocker`.

I have tried the following command in an attempt to generate mocks in a different package/directory from the source file:
```
//go:generate gomocker gen MyInterface --force --package mock --output ../../gen/mock/my_interface_mock.go
```

This works when `../../gen/mock` already exists but fails with the following error if it doesn't:
```
Error: open ../../gen/mock/my_interface_mock.go: no such file or directory
```

So right now it seems we just need to create directories when they don't exist in order to support the function stated in this feature request.

The reason of this request is that it's easier to have all mocks in a separate directory if we do some bulk operations on generated files (say, excluding them from format checks).

**Comment by jauhararifin** [comment]
Thank you for the feature request, or rather a bug report. I think ideally it should create a new dir if the output dir doesn't exist. 
I created [this PR](https://github.com/jauhararifin/gomocker/pull/4) to add this improvement. Can you check it it works?

**Comment by WJY-norainu** [comment]
Hi @jauhararifin thanks - the PR works.
Btw, it seems the version number for `gomocker` is hard-coded [here](https://github.com/jauhararifin/gomocker/blob/master/gomocker/main.go#L5). Does it need to be incremented every time ith new release? 🤔 

Embedding version numbers in binary is supported by go1.18 but earlier versions may require some workarounds (quick google search suggests to use build flags or `go embed`). I'm not sure if those workarounds will work for binaries pulled by `go install ` command though.

**Comment by jauhararifin** [comment]
> Hi @jauhararifin thanks - the PR works.

Ok, thank you. I merged the PR. You can use version [1.0.6](https://github.com/jauhararifin/gomocker/releases/tag/v1.0.6) to use it.

> Btw, it seems the version number for gomocker is hard-coded [here](https://github.com/jauhararifin/gomocker/blob/master/gomocker/main.go#L5). Does it need to be incremented every time ith new release? thinking

I updated the PR to automate the version numbering as well.
I tested installing it by running `go install github.com/jauhararifin/gomocker/gomocker@v1.0.6`, and the version is updated correctly.

**Comment by WJY-norainu** [comment]
Thanks a lot - good to close this issue.
